// ignore_for_file: constant_identifier_names

import 'alimentos_provider.dart';

const TIPO_ALIMENTO_LIST = [
  'Frutas',
  'Verduras',
  'Leguminosas',
  'Alimentos de origen animal',
  'Cereales',
  'Leche',
  'Aceites y grasas',
  'Aceites y grasas con proteinas',
  'Azúcares',
  'Alimentos libres en energía',
  'Supermercado',
  'Otros',
];
const TIPO_ALIMENTO_MAP = {
  'Frutas': 1,
  'Verduras': 2,
  'Leguminosas': 3,
  'Alimentos de origen animal': 4,
  'Cereales': 5
};

final recetas = {
  /*'0001': RecetaItem(
      id: '0001',
      nombre: 'Entomatadas verdes',
      resumen: 'Entomatadas verdes con cebolla, calabaza y coliflor al horno',
      porciones: 4,
      alimentos: {
        '10001': 2,
        '10004': 4,
      }),
  '0002': RecetaItem(
      id: '0002',
      nombre: 'Bocoles',
      resumen: 'Bocoles de salsa verde y huevo con chorizo',
      porciones: 2,
      alimentos: {
        '10001': 2,
        '10004': 4,
        '10003': 1,
        '10009': 7,
        '10007': 4,
      }),
  '0003': RecetaItem(
      id: '0003',
      nombre: 'Pavo asado',
      resumen:
          'Exquisito pavo asado a las brazas con pato, ganzo y vampiro a la veracruzana, para 4 personas hecho en horno a la leña',
      porciones: 2,
      alimentos: {
        '10001': 2,
        '10004': 4,
        '10003': 1,
        '10009': 2,
        '10007': 4,
        '10010': 8,
        '10002': 2,
      }),*/
};

final alimentos = {
  '10001': AlimentoItem(
    id: '10001',
    nombre: 'Acelga cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 120,
      peso_neto_g: 98,
      energia_kcal: 22,
      proteina_g: 2.2,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.3,
      fibra_g: 3.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10002': AlimentoItem(
    id: '10002',
    nombre: 'Acelga picada cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 72,
      peso_neto_g: 72,
      energia_kcal: 19,
      proteina_g: 1.9,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.9,
      fibra_g: 2.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10003': AlimentoItem(
    id: '10003',
    nombre: 'Alcachofa mediana cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 120,
      peso_neto_g: 48,
      energia_kcal: 25,
      proteina_g: 1.4,
      lipidos_g: 0.2,
      hidra_carbo_g: 5.7,
      fibra_g: 4.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10004': AlimentoItem(
    id: '10004',
    nombre: 'Apio cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3 / 4,
      unidad: '	taza	',
      peso_bruto_g: 113,
      peso_neto_g: 113,
      energia_kcal: 20,
      proteina_g: 0.9,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.5,
      fibra_g: 1.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10005': AlimentoItem(
    id: '10005',
    nombre: 'Apio crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1.5,
      unidad: '	taza	',
      peso_bruto_g: 152,
      peso_neto_g: 135,
      energia_kcal: 22,
      proteina_g: 0.9,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.0,
      fibra_g: 2.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10006': AlimentoItem(
    id: '10006',
    nombre: 'Arúgula, cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	taza	',
      peso_bruto_g: 80,
      peso_neto_g: 80,
      energia_kcal: 20,
      proteina_g: 2.1,
      lipidos_g: 0.5,
      hidra_carbo_g: 2.9,
      fibra_g: 3.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10007': AlimentoItem(
    id: '10007',
    nombre: 'Berenjena picada cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 99,
      peso_neto_g: 99,
      energia_kcal: 35,
      proteina_g: 0.8,
      lipidos_g: 0.2,
      hidra_carbo_g: 8.6,
      fibra_g: 2.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10008': AlimentoItem(
    id: '10008',
    nombre: 'Berro crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 68,
      peso_neto_g: 56,
      energia_kcal: 34,
      proteina_g: 1.3,
      lipidos_g: 0.1,
      hidra_carbo_g: 0.7,
      fibra_g: 0.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10009': AlimentoItem(
    id: '10009',
    nombre: 'Betabel crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	pieza	',
      peso_bruto_g: 43,
      peso_neto_g: 39,
      energia_kcal: 19,
      proteina_g: 0.8,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.3,
      fibra_g: 0.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10010': AlimentoItem(
    id: '10010',
    nombre: 'Betabel crudo rallado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	taza	',
      peso_bruto_g: 38,
      peso_neto_g: 38,
      energia_kcal: 18,
      proteina_g: 0.8,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.1,
      fibra_g: 0.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10011': AlimentoItem(
    id: '10011',
    nombre: 'Bledos crudos',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 150,
      unidad: '	g	',
      peso_bruto_g: 150,
      peso_neto_g: 95,
      energia_kcal: 27,
      proteina_g: 2.4,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.8,
      fibra_g: 0.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10012': AlimentoItem(
    id: '10012',
    nombre: 'Brócoli cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 92,
      peso_neto_g: 92,
      energia_kcal: 26,
      proteina_g: 2.7,
      lipidos_g: 0.4,
      hidra_carbo_g: 4.6,
      fibra_g: 2.7,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10013': AlimentoItem(
    id: '10013',
    nombre: 'Brócoli crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 88,
      peso_neto_g: 71,
      energia_kcal: 19,
      proteina_g: 2.1,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.7,
      fibra_g: 2.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10014': AlimentoItem(
    id: '10014',
    nombre: 'Calabacita alargada cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 111,
      peso_neto_g: 91,
      energia_kcal: 21,
      proteina_g: 1.6,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.4,
      fibra_g: 1.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10015': AlimentoItem(
    id: '10015',
    nombre: 'Calabacita redonda cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 100,
      peso_neto_g: 79,
      energia_kcal: 18,
      proteina_g: 1.4,
      lipidos_g: 0.1,
      hidra_carbo_g: 2.9,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10016': AlimentoItem(
    id: '10016',
    nombre: 'Calabacita de Castilla cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 110,
      peso_neto_g: 110,
      energia_kcal: 22,
      proteina_g: 0.8,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.4,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10017': AlimentoItem(
    id: '10017',
    nombre: 'Cebolla blanca rebanada',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 58,
      peso_neto_g: 58,
      energia_kcal: 23,
      proteina_g: 0.6,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.4,
      fibra_g: 1.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10018': AlimentoItem(
    id: '10018',
    nombre: 'Cebolla cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	taza	',
      peso_bruto_g: 53,
      peso_neto_g: 53,
      energia_kcal: 23,
      proteina_g: 0.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.3,
      fibra_g: 0.7,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10019': AlimentoItem(
    id: '10019',
    nombre: 'Cebolla morada rebanada',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 58,
      peso_neto_g: 58,
      energia_kcal: 20,
      proteina_g: 0.5,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.4,
      fibra_g: 0.7,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10020': AlimentoItem(
    id: '10020',
    nombre: 'Cebollita de cambray sin raíz',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3,
      unidad: '	pieza	',
      peso_bruto_g: 75,
      peso_neto_g: 72,
      energia_kcal: 23,
      proteina_g: 1.3,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.3,
      fibra_g: 1.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10021': AlimentoItem(
    id: '10021',
    nombre: 'Cebollita en salmuera',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 95,
      peso_neto_g: 95,
      energia_kcal: 24,
      proteina_g: 0.9,
      lipidos_g: 0.2,
      hidra_carbo_g: 6.7,
      fibra_g: 1.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10022': AlimentoItem(
    id: '10022',
    nombre: 'Champiñon cocido entero',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 78,
      peso_neto_g: 78,
      energia_kcal: 20,
      proteina_g: 2.8,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.2,
      fibra_g: 1.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10023': AlimentoItem(
    id: '10023',
    nombre: 'Champiñon cocido rebanado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 70,
      peso_neto_g: 70,
      energia_kcal: 18,
      proteina_g: 2.5,
      lipidos_g: 0.2,
      hidra_carbo_g: 2.8,
      fibra_g: 1.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10024': AlimentoItem(
    id: '10024',
    nombre: 'Champiñon crudo entero',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 96,
      peso_neto_g: 93,
      energia_kcal: 20,
      proteina_g: 2.9,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.1,
      fibra_g: 0.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10025': AlimentoItem(
    id: '10025',
    nombre: 'Champíñon crudo rebanado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1.5,
      unidad: '	taza	',
      peso_bruto_g: 105,
      peso_neto_g: 105,
      energia_kcal: 23,
      proteina_g: 3.2,
      lipidos_g: 0.4,
      hidra_carbo_g: 3.4,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10026': AlimentoItem(
    id: '10026',
    nombre: 'Chayote cocido picado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 80,
      peso_neto_g: 80,
      energia_kcal: 19,
      proteina_g: 0.5,
      lipidos_g: 0.4,
      hidra_carbo_g: 4.1,
      fibra_g: 2.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10027': AlimentoItem(
    id: '10027',
    nombre: 'Chayote crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	pieza	',
      peso_bruto_g: 102,
      peso_neto_g: 100,
      energia_kcal: 19,
      proteina_g: 0.8,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.5,
      fibra_g: 1.7,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10028': AlimentoItem(
    id: '10028',
    nombre: 'Chepil crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 70,
      unidad: '	g	',
      peso_bruto_g: 70,
      peso_neto_g: 41,
      energia_kcal: 26,
      proteina_g: 2.8,
      lipidos_g: 0.2,
      hidra_carbo_g: 3.0,
      fibra_g: 0.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10029': AlimentoItem(
    id: '10029',
    nombre: 'Chícharo cocido sin vaina',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	taza	',
      peso_bruto_g: 40,
      peso_neto_g: 40,
      energia_kcal: 34,
      proteina_g: 2.1,
      lipidos_g: 0.1,
      hidra_carbo_g: 6.1,
      fibra_g: 2.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10030': AlimentoItem(
    id: '10030',
    nombre: 'Chicharo cocido con vaina',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 73,
      peso_neto_g: 28,
      energia_kcal: 22,
      proteina_g: 1.5,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.0,
      fibra_g: 1.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10031': AlimentoItem(
    id: '10031',
    nombre: 'Chicharo en vaina cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 3,
      unidad: '	taza	',
      peso_bruto_g: 53,
      peso_neto_g: 53,
      energia_kcal: 21,
      proteina_g: 1.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.4,
      fibra_g: 1.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10032': AlimentoItem(
    id: '10032',
    nombre: 'Chicoria cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 140,
      unidad: '	g	',
      peso_bruto_g: 140,
      peso_neto_g: 120,
      energia_kcal: 24,
      proteina_g: 1.4,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.1,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10033': AlimentoItem(
    id: '10033',
    nombre: 'Chalacas crudas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3,
      unidad: '	pieza	',
      peso_bruto_g: 90,
      peso_neto_g: 76,
      energia_kcal: 24,
      proteina_g: 1.1,
      lipidos_g: 0.2,
      hidra_carbo_g: 5.5,
      fibra_g: 0.7,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10034': AlimentoItem(
    id: '10034',
    nombre: 'Chilacayote crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 150,
      unidad: '	g	',
      peso_bruto_g: 150,
      peso_neto_g: 135,
      energia_kcal: 19,
      proteina_g: 1.6,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.6,
      fibra_g: 0.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10035': AlimentoItem(
    id: '10035',
    nombre: 'Chile chilaca',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	pieza	',
      peso_bruto_g: 60,
      peso_neto_g: 50,
      energia_kcal: 20,
      proteina_g: 0.8,
      lipidos_g: 0.2,
      hidra_carbo_g: 3.7,
      fibra_g: 0.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10036': AlimentoItem(
    id: '10036',
    nombre: 'Chile chipotle seco',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	pieza	',
      peso_bruto_g: 10,
      peso_neto_g: 8,
      energia_kcal: 29,
      proteina_g: 1.2,
      lipidos_g: 0.5,
      hidra_carbo_g: 4.8,
      fibra_g: 0.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10037': AlimentoItem(
    id: '10037',
    nombre: 'Chile costeño',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	pieza	',
      peso_bruto_g: 64,
      peso_neto_g: 54,
      energia_kcal: 17,
      proteina_g: 0.9,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.9,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10038': AlimentoItem(
    id: '10038',
    nombre: 'Chile cristalino',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	pieza	',
      peso_bruto_g: 64,
      peso_neto_g: 54,
      energia_kcal: 20,
      proteina_g: 0.9,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.9,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10039': AlimentoItem(
    id: '10039',
    nombre: 'Chile cuaresmeño',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	pieza	',
      peso_bruto_g: 60,
      peso_neto_g: 50,
      energia_kcal: 16,
      proteina_g: 0.8,
      lipidos_g: 0.2,
      hidra_carbo_g: 3.7,
      fibra_g: 0.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10040': AlimentoItem(
    id: '10040',
    nombre: 'Chile de árbol seco',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	pieza	',
      peso_bruto_g: 8,
      peso_neto_g: 7,
      energia_kcal: 21,
      proteina_g: 0.9,
      lipidos_g: 0.4,
      hidra_carbo_g: 4.3,
      fibra_g: 2.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10041': AlimentoItem(
    id: '10041',
    nombre: 'Chile habanero',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 5,
      unidad: '	pieza	',
      peso_bruto_g: 80,
      peso_neto_g: 67,
      energia_kcal: 25,
      proteina_g: 1.5,
      lipidos_g: 0.5,
      hidra_carbo_g: 3.6,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10042': AlimentoItem(
    id: '10042',
    nombre: 'Chile jalapeño',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 6,
      unidad: '	pieza	',
      peso_bruto_g: 90,
      peso_neto_g: 78,
      energia_kcal: 23,
      proteina_g: 1.1,
      lipidos_g: 0.5,
      hidra_carbo_g: 4.6,
      fibra_g: 2.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10043': AlimentoItem(
    id: '10043',
    nombre: 'Chile poblano',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	pieza	',
      peso_bruto_g: 40,
      peso_neto_g: 32,
      energia_kcal: 15,
      proteina_g: 0.8,
      lipidos_g: 0.2,
      hidra_carbo_g: 3.3,
      fibra_g: 0.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10044': AlimentoItem(
    id: '10044',
    nombre: 'Chiles secos',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 10,
      unidad: '	g	',
      peso_bruto_g: 10,
      peso_neto_g: 7,
      energia_kcal: 23,
      proteina_g: 0.8,
      lipidos_g: 0.7,
      hidra_carbo_g: 4.3,
      fibra_g: 0.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10045': AlimentoItem(
    id: '10045',
    nombre: 'Cilantro picado crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 120,
      peso_neto_g: 120,
      energia_kcal: 28,
      proteina_g: 2.6,
      lipidos_g: 0.6,
      hidra_carbo_g: 4.4,
      fibra_g: 3.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10046': AlimentoItem(
    id: '10046',
    nombre: 'Clavito (hongo) crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 75,
      peso_neto_g: 71,
      energia_kcal: 28,
      proteina_g: 4.3,
      lipidos_g: 0.4,
      hidra_carbo_g: 3.8,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10047': AlimentoItem(
    id: '10047',
    nombre: 'Col cocida picada',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 75,
      peso_neto_g: 75,
      energia_kcal: 17,
      proteina_g: 1.0,
      lipidos_g: 0.0,
      hidra_carbo_g: 4.1,
      fibra_g: 1.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10048': AlimentoItem(
    id: '10048',
    nombre: 'Col cruda picada',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 140,
      peso_neto_g: 112,
      energia_kcal: 27,
      proteina_g: 1.4,
      lipidos_g: 0.2,
      hidra_carbo_g: 6.0,
      fibra_g: 2.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10049': AlimentoItem(
    id: '10049',
    nombre: 'Col morada cruda picada',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 70,
      peso_neto_g: 56,
      energia_kcal: 17,
      proteina_g: 0.8,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.1,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10050': AlimentoItem(
    id: '10050',
    nombre: 'Colesita de Bruselas cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3,
      unidad: '	pieza	',
      peso_bruto_g: 63,
      peso_neto_g: 63,
      energia_kcal: 23,
      proteina_g: 1.6,
      lipidos_g: 0.3,
      hidra_carbo_g: 4.5,
      fibra_g: 1.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10051': AlimentoItem(
    id: '10051',
    nombre: 'Coliflor cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 125,
      peso_neto_g: 125,
      energia_kcal: 28,
      proteina_g: 2.3,
      lipidos_g: 0.6,
      hidra_carbo_g: 5.1,
      fibra_g: 2.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10052': AlimentoItem(
    id: '10052',
    nombre: 'Coliflor cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 200,
      peso_neto_g: 80,
      energia_kcal: 20,
      proteina_g: 1.6,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.2,
      fibra_g: 2.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10053': AlimentoItem(
    id: '10053',
    nombre: 'Coliflor verde cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 68,
      peso_neto_g: 68,
      energia_kcal: 22,
      proteina_g: 2.1,
      lipidos_g: 2.1,
      hidra_carbo_g: 4.2,
      fibra_g: 2.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10054': AlimentoItem(
    id: '10054',
    nombre: 'Coliflor verde cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 128,
      peso_neto_g: 78,
      energia_kcal: 24,
      proteina_g: 2.3,
      lipidos_g: 2.3,
      hidra_carbo_g: 4.8,
      fibra_g: 2.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10055': AlimentoItem(
    id: '10055',
    nombre: 'Colinabo crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 90,
      unidad: '	g	',
      peso_bruto_g: 90,
      peso_neto_g: 66,
      energia_kcal: 22,
      proteina_g: 1.1,
      lipidos_g: 1.1,
      hidra_carbo_g: 4.1,
      fibra_g: 1.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10056': AlimentoItem(
    id: '10056',
    nombre: 'Cozarón de alcachofa crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 25,
      peso_neto_g: 25,
      energia_kcal: 16,
      proteina_g: 0.6,
      lipidos_g: 0.6,
      hidra_carbo_g: 4.1,
      fibra_g: 0.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10057': AlimentoItem(
    id: '10057',
    nombre: 'Corazón de lechuga crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 130,
      peso_neto_g: 124,
      energia_kcal: 12,
      proteina_g: 1.2,
      lipidos_g: 1.2,
      hidra_carbo_g: 4.4,
      fibra_g: 1.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10058': AlimentoItem(
    id: '10058',
    nombre: 'Corazón de palmito crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3,
      unidad: '	pieza	',
      peso_bruto_g: 99,
      peso_neto_g: 99,
      energia_kcal: 27,
      proteina_g: 2.4,
      lipidos_g: 2.4,
      hidra_carbo_g: 4.5,
      fibra_g: 2.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10059': AlimentoItem(
    id: '10059',
    nombre: 'Cresón cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 135,
      peso_neto_g: 135,
      energia_kcal: 31,
      proteina_g: 2.6,
      lipidos_g: 2.6,
      hidra_carbo_g: 5.2,
      fibra_g: 1.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10060': AlimentoItem(
    id: '10060',
    nombre: 'Cresón limpio crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 100,
      peso_neto_g: 100,
      energia_kcal: 32,
      proteina_g: 2.8,
      lipidos_g: 2.8,
      hidra_carbo_g: 5.6,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10061': AlimentoItem(
    id: '10061',
    nombre: 'Crucetas crudas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 150,
      unidad: '	g	',
      peso_bruto_g: 150,
      peso_neto_g: 117,
      energia_kcal: 21,
      proteina_g: 1.3,
      lipidos_g: 1.3,
      hidra_carbo_g: 4.3,
      fibra_g: 0.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10062': AlimentoItem(
    id: '10062',
    nombre: 'Cuitlacoche cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 3,
      unidad: '	taza	',
      peso_bruto_g: 66,
      peso_neto_g: 66,
      energia_kcal: 20,
      proteina_g: 0.8,
      lipidos_g: 0.8,
      hidra_carbo_g: 4.1,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10063': AlimentoItem(
    id: '10063',
    nombre: 'Echalot',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 40,
      peso_neto_g: 34,
      energia_kcal: 25,
      proteina_g: 0.9,
      lipidos_g: 0.9,
      hidra_carbo_g: 5.8,
      fibra_g: 0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10064': AlimentoItem(
    id: '10064',
    nombre: 'Ejotes cocidos picados',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 63,
      peso_neto_g: 63,
      energia_kcal: 22,
      proteina_g: 1.2,
      lipidos_g: 1.2,
      hidra_carbo_g: 4.9,
      fibra_g: 2.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10065': AlimentoItem(
    id: '10065',
    nombre: 'Elotitos de cambray',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 8,
      unidad: '	pieza	',
      peso_bruto_g: 64,
      peso_neto_g: 64,
      energia_kcal: 26,
      proteina_g: 2.1,
      lipidos_g: 2.1,
      hidra_carbo_g: 4.3,
      fibra_g: 1.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10066': AlimentoItem(
    id: '10066',
    nombre: 'Envidia cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3,
      unidad: '	taza	',
      peso_bruto_g: 150,
      peso_neto_g: 129,
      energia_kcal: 22,
      proteina_g: 1.6,
      lipidos_g: 1.6,
      hidra_carbo_g: 4.3,
      fibra_g: 4.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10067': AlimentoItem(
    id: '10067',
    nombre: 'Espárragos crudos',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 6,
      unidad: '	pieza	',
      peso_bruto_g: 90,
      peso_neto_g: 90,
      energia_kcal: 22,
      proteina_g: 2.3,
      lipidos_g: 2.3,
      hidra_carbo_g: 3.8,
      fibra_g: 2.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10068': AlimentoItem(
    id: '10068',
    nombre: 'Espinaca cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 90,
      peso_neto_g: 90,
      energia_kcal: 21,
      proteina_g: 2.7,
      lipidos_g: 2.7,
      hidra_carbo_g: 3.4,
      fibra_g: 3.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10069': AlimentoItem(
    id: '10069',
    nombre: 'Espinaca cruda picada',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 120,
      peso_neto_g: 120,
      energia_kcal: 28,
      proteina_g: 3.4,
      lipidos_g: 3.4,
      hidra_carbo_g: 4.4,
      fibra_g: 2.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10070': AlimentoItem(
    id: '10070',
    nombre: 'Flor de calabaza cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 134,
      peso_neto_g: 134,
      energia_kcal: 20,
      proteina_g: 1.4,
      lipidos_g: 1.4,
      hidra_carbo_g: 4.4,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10071': AlimentoItem(
    id: '10071',
    nombre: 'Flor de calabaza cruda picada',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	taza	',
      peso_bruto_g: 132,
      peso_neto_g: 132,
      energia_kcal: 20,
      proteina_g: 1.2,
      lipidos_g: 1.2,
      hidra_carbo_g: 4.4,
      fibra_g: 0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10072': AlimentoItem(
    id: '10072',
    nombre: 'Flor de colorín cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 40,
      peso_neto_g: 40,
      energia_kcal: 24,
      proteina_g: 1.8,
      lipidos_g: 1.8,
      hidra_carbo_g: 4.0,
      fibra_g: 1.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10073': AlimentoItem(
    id: '10073',
    nombre: 'Flor de colorín cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 40,
      peso_neto_g: 40,
      energia_kcal: 24,
      proteina_g: 1.8,
      lipidos_g: 1.8,
      hidra_carbo_g: 4.0,
      fibra_g: 1.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10074': AlimentoItem(
    id: '10074',
    nombre: 'Flor de garambullo cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 50,
      unidad: '	g	',
      peso_bruto_g: 50,
      peso_neto_g: 50,
      energia_kcal: 19,
      proteina_g: 0.4,
      lipidos_g: 0.4,
      hidra_carbo_g: 4.1,
      fibra_g: 0.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10075': AlimentoItem(
    id: '10075',
    nombre: 'Flor de maguey cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 60,
      unidad: '	g	',
      peso_bruto_g: 60,
      peso_neto_g: 60,
      energia_kcal: 21,
      proteina_g: 0.5,
      lipidos_g: 0.5,
      hidra_carbo_g: 4.4,
      fibra_g: 0.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10076': AlimentoItem(
    id: '10076',
    nombre: 'Flor de Yuca cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 75,
      unidad: '	g	',
      peso_bruto_g: 75,
      peso_neto_g: 75,
      energia_kcal: 29,
      proteina_g: 2.0,
      lipidos_g: 2.0,
      hidra_carbo_g: 4.5,
      fibra_g: 0.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10077': AlimentoItem(
    id: '10077',
    nombre: 'Germen de alfalfa cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3,
      unidad: '	taza	',
      peso_bruto_g: 99,
      peso_neto_g: 99,
      energia_kcal: 23,
      proteina_g: 4.0,
      lipidos_g: 4.0,
      hidra_carbo_g: 2.1,
      fibra_g: 1.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10078': AlimentoItem(
    id: '10078',
    nombre: 'Germen de lenteja crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	taza	',
      peso_bruto_g: 19,
      peso_neto_g: 19,
      energia_kcal: 20,
      proteina_g: 1.7,
      lipidos_g: 1.7,
      hidra_carbo_g: 4.3,
      fibra_g: 0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10079': AlimentoItem(
    id: '10079',
    nombre: 'Germen de soya cocidpo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 3,
      unidad: '	taza	',
      peso_bruto_g: 31,
      peso_neto_g: 31,
      energia_kcal: 25,
      proteina_g: 2.7,
      lipidos_g: 1.4,
      hidra_carbo_g: 2.1,
      fibra_g: 0.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10080': AlimentoItem(
    id: '10080',
    nombre: 'Granos de elote crudos',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	cuchara	',
      peso_bruto_g: 21,
      peso_neto_g: 21,
      energia_kcal: 18,
      proteina_g: 0.7,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.0,
      fibra_g: 0.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10081': AlimentoItem(
    id: '10081',
    nombre: 'Haba verde',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	pieza	',
      peso_bruto_g: 32,
      peso_neto_g: 32,
      energia_kcal: 23,
      proteina_g: 1.8,
      lipidos_g: 0.2,
      hidra_carbo_g: 3.7,
      fibra_g: 1.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10082': AlimentoItem(
    id: '10082',
    nombre: 'Hojas de amaranto cocidas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 100,
      unidad: '	g	',
      peso_bruto_g: 100,
      peso_neto_g: 100,
      energia_kcal: 21,
      proteina_g: 2.1,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.1,
      fibra_g: 0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10083': AlimentoItem(
    id: '10083',
    nombre: 'Hojas de amaranto crudas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 6,
      unidad: '	hojas	',
      peso_bruto_g: 84,
      peso_neto_g: 84,
      energia_kcal: 19,
      proteina_g: 2.1,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.4,
      fibra_g: 0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10084': AlimentoItem(
    id: '10084',
    nombre: 'Hojas de chicoria cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 130,
      unidad: '	g	',
      peso_bruto_g: 130,
      peso_neto_g: 130,
      energia_kcal: 26,
      proteina_g: 1.6,
      lipidos_g: 0.3,
      hidra_carbo_g: 4.4,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10085': AlimentoItem(
    id: '10085',
    nombre: 'Hojas de dientes de león',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 50,
      unidad: '	g	',
      peso_bruto_g: 50,
      peso_neto_g: 45,
      energia_kcal: 24,
      proteina_g: 1.2,
      lipidos_g: 0.3,
      hidra_carbo_g: 4.1,
      fibra_g: 0.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10086': AlimentoItem(
    id: '10086',
    nombre: 'Hojas de pata de paloma',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 30,
      unidad: '	g	',
      peso_bruto_g: 30,
      peso_neto_g: 25,
      energia_kcal: 20,
      proteina_g: 0.8,
      lipidos_g: 0.4,
      hidra_carbo_g: 4.2,
      fibra_g: 0.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10087': AlimentoItem(
    id: '10087',
    nombre: 'Hojas de remolacha,  crudas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	hojas	',
      peso_bruto_g: 64,
      peso_neto_g: 64,
      energia_kcal: 14,
      proteina_g: 1.4,
      lipidos_g: 0.1,
      hidra_carbo_g: 2.8,
      fibra_g: 2.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10088': AlimentoItem(
    id: '10088',
    nombre: 'Hojas de remolacha, hervida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 72,
      peso_neto_g: 72,
      energia_kcal: 19,
      proteina_g: 1.9,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.9,
      fibra_g: 2.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10089': AlimentoItem(
    id: '10089',
    nombre: 'Hongos porrtobello crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 84,
      peso_neto_g: 81,
      energia_kcal: 21,
      proteina_g: 2.0,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.1,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10090': AlimentoItem(
    id: '10090',
    nombre: 'Hongos shiitake deshidratados',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 4,
      peso_neto_g: 4,
      energia_kcal: 11,
      proteina_g: 0.3,
      lipidos_g: 0.0,
      hidra_carbo_g: 2.7,
      fibra_g: 0.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10091': AlimentoItem(
    id: '10091',
    nombre: 'Hongos crudos',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 70,
      peso_neto_g: 63,
      energia_kcal: 17,
      proteina_g: 2.0,
      lipidos_g: 0.3,
      hidra_carbo_g: 2.8,
      fibra_g: 1.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10092': AlimentoItem(
    id: '10092',
    nombre: 'Huanzontle',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 40,
      peso_neto_g: 40,
      energia_kcal: 24,
      proteina_g: 1.8,
      lipidos_g: 0.3,
      hidra_carbo_g: 4.8,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10093': AlimentoItem(
    id: '10093',
    nombre: 'Huitlacoche cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 3,
      unidad: '	taza	',
      peso_bruto_g: 66,
      peso_neto_g: 66,
      energia_kcal: 20,
      proteina_g: 8.0,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.1,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10094': AlimentoItem(
    id: '10094',
    nombre: 'Ibes frescos',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 30,
      unidad: '	g	',
      peso_bruto_g: 30,
      peso_neto_g: 17,
      energia_kcal: 22,
      proteina_g: 1.7,
      lipidos_g: 0.0,
      hidra_carbo_g: 3.6,
      fibra_g: 0.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10095': AlimentoItem(
    id: '10095',
    nombre: 'Jicama picada',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 60,
      peso_neto_g: 60,
      energia_kcal: 23,
      proteina_g: 4.0,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.3,
      fibra_g: 2.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10096': AlimentoItem(
    id: '10096',
    nombre: 'Jitomate',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 120,
      unidad: '	g	',
      peso_bruto_g: 120,
      peso_neto_g: 113,
      energia_kcal: 20,
      proteina_g: 1.0,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.4,
      fibra_g: 1.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10097': AlimentoItem(
    id: '10097',
    nombre: 'Jitomate bola',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 123,
      peso_neto_g: 108,
      energia_kcal: 19,
      proteina_g: 1.0,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.2,
      fibra_g: 1.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10098': AlimentoItem(
    id: '10098',
    nombre: 'Jitomate cereza',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	pieza	',
      peso_bruto_g: 100,
      peso_neto_g: 95,
      energia_kcal: 17,
      proteina_g: 0.8,
      lipidos_g: 0.2,
      hidra_carbo_g: 3.7,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10099': AlimentoItem(
    id: '10099',
    nombre: 'Jitomate deshidratado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 5,
      unidad: '	pieza	',
      peso_bruto_g: 10,
      peso_neto_g: 10,
      energia_kcal: 23,
      proteina_g: 1.5,
      lipidos_g: 0.5,
      hidra_carbo_g: 4.3,
      fibra_g: 2.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10100': AlimentoItem(
    id: '10100',
    nombre: 'Jitomate guaje o saladet',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	pieza	',
      peso_bruto_g: 130,
      peso_neto_g: 124,
      energia_kcal: 22,
      proteina_g: 1.1,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.8,
      fibra_g: 1.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10101': AlimentoItem(
    id: '10101',
    nombre: 'Jitomate verde',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 123,
      peso_neto_g: 123,
      energia_kcal: 28,
      proteina_g: 1.5,
      lipidos_g: 0.2,
      hidra_carbo_g: 6.3,
      fibra_g: 1.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10102': AlimentoItem(
    id: '10102',
    nombre: 'Jitomatillo (miltomate)',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 70,
      unidad: '	g	',
      peso_bruto_g: 70,
      peso_neto_g: 60,
      energia_kcal: 21,
      proteina_g: 0.9,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.3,
      fibra_g: 0.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10103': AlimentoItem(
    id: '10103',
    nombre: 'Jugo de tomate',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 122,
      peso_neto_g: 122,
      energia_kcal: 21,
      proteina_g: 0.9,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.1,
      fibra_g: 0.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10104': AlimentoItem(
    id: '10104',
    nombre: 'Jugo de verduras',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 121,
      peso_neto_g: 121,
      energia_kcal: 23,
      proteina_g: 0.8,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.5,
      fibra_g: 1.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10105': AlimentoItem(
    id: '10105',
    nombre: 'Jugo de zanahoria',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	taza	',
      peso_bruto_g: 59,
      peso_neto_g: 59,
      energia_kcal: 24,
      proteina_g: 0.6,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.5,
      fibra_g: 0.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10106': AlimentoItem(
    id: '10106',
    nombre: 'Lechuga',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3,
      unidad: '	taza	',
      peso_bruto_g: 141,
      peso_neto_g: 135,
      energia_kcal: 23,
      proteina_g: 1.7,
      lipidos_g: 0.4,
      hidra_carbo_g: 4.5,
      fibra_g: 2.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10107': AlimentoItem(
    id: '10107',
    nombre: 'Lengua de vaca',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 110,
      unidad: '	g	',
      peso_bruto_g: 110,
      peso_neto_g: 99,
      energia_kcal: 27,
      proteina_g: 2.0,
      lipidos_g: 0.7,
      hidra_carbo_g: 3.2,
      fibra_g: 0.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10108': AlimentoItem(
    id: '10108',
    nombre: 'Lenteja germinada cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	taza	',
      peso_bruto_g: 19,
      peso_neto_g: 19,
      energia_kcal: 19,
      proteina_g: 1.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.1,
      fibra_g: 0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10109': AlimentoItem(
    id: '10109',
    nombre: 'Malva',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 100,
      unidad: '	g	',
      peso_bruto_g: 100,
      peso_neto_g: 85,
      energia_kcal: 34,
      proteina_g: 4.1,
      lipidos_g: 0.5,
      hidra_carbo_g: 3.3,
      fibra_g: 0.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10110': AlimentoItem(
    id: '10110',
    nombre: 'Mezcla de verduras congeladas, cocidas sin sal',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 46,
      peso_neto_g: 46,
      energia_kcal: 30,
      proteina_g: 1.3,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.6,
      fibra_g: 2.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10111': AlimentoItem(
    id: '10111',
    nombre: 'Morillas deshidratadas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 10,
      unidad: '	g	',
      peso_bruto_g: 10,
      peso_neto_g: 10,
      energia_kcal: 27,
      proteina_g: 3.2,
      lipidos_g: 0.4,
      hidra_carbo_g: 4.4,
      fibra_g: 2.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10112': AlimentoItem(
    id: '10112',
    nombre: 'Morillas frescas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 110,
      unidad: '	g	',
      peso_bruto_g: 110,
      peso_neto_g: 94,
      energia_kcal: 25,
      proteina_g: 3.0,
      lipidos_g: 0.4,
      hidra_carbo_g: 4.1,
      fibra_g: 2.3,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10113': AlimentoItem(
    id: '10113',
    nombre: 'Nabo cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 150,
      unidad: '	g	',
      peso_bruto_g: 150,
      peso_neto_g: 99,
      energia_kcal: 22,
      proteina_g: 0.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.0,
      fibra_g: 2.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10114': AlimentoItem(
    id: '10114',
    nombre: 'Nopal cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 149,
      peso_neto_g: 149,
      energia_kcal: 22,
      proteina_g: 2.0,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.9,
      fibra_g: 3.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10115': AlimentoItem(
    id: '10115',
    nombre: 'Nopal crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	pieza	',
      peso_bruto_g: 140,
      peso_neto_g: 134,
      energia_kcal: 22,
      proteina_g: 1.8,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.5,
      fibra_g: 3.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10116': AlimentoItem(
    id: '10116',
    nombre: 'Nopal crudo de cambray',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	pieza	',
      peso_bruto_g: 100,
      peso_neto_g: 100,
      energia_kcal: 27,
      proteina_g: 1.7,
      lipidos_g: 0.3,
      hidra_carbo_g: 2.9,
      fibra_g: 3.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10117': AlimentoItem(
    id: '10117',
    nombre: 'Palmito, enlatado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 33,
      peso_neto_g: 33,
      energia_kcal: 30,
      proteina_g: 0.8,
      lipidos_g: 0.2,
      hidra_carbo_g: 1.5,
      fibra_g: 0.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10118': AlimentoItem(
    id: '10118',
    nombre: 'Papaloquite crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 120,
      peso_neto_g: 108,
      energia_kcal: 24,
      proteina_g: 1.9,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.1,
      fibra_g: 1.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10119': AlimentoItem(
    id: '10119',
    nombre: 'Papilla de verduras mixtas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 3,
      unidad: '	frasco	',
      peso_bruto_g: 43,
      peso_neto_g: 43,
      energia_kcal: 19,
      proteina_g: 0.5,
      lipidos_g: 0.0,
      hidra_carbo_g: 4.1,
      fibra_g: 0.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10120': AlimentoItem(
    id: '10120',
    nombre: 'Pepinillos crudos',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 3,
      unidad: '	taza	',
      peso_bruto_g: 80,
      peso_neto_g: 80,
      energia_kcal: 23,
      proteina_g: 1.1,
      lipidos_g: 1.0,
      hidra_carbo_g: 3.3,
      fibra_g: 0.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10121': AlimentoItem(
    id: '10121',
    nombre: 'Pepinillos dulces',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	cuchara	',
      peso_bruto_g: 15,
      peso_neto_g: 15,
      energia_kcal: 20,
      proteina_g: 0.1,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.3,
      fibra_g: 0.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10122': AlimentoItem(
    id: '10122',
    nombre: 'Pepino con cáscara rebanado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 104,
      peso_neto_g: 104,
      energia_kcal: 16,
      proteina_g: 0.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.8,
      fibra_g: 0.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10123': AlimentoItem(
    id: '10123',
    nombre: 'Perejil crudo picado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 60,
      peso_neto_g: 60,
      energia_kcal: 22,
      proteina_g: 1.8,
      lipidos_g: 0.5,
      hidra_carbo_g: 3.8,
      fibra_g: 2.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10124': AlimentoItem(
    id: '10124',
    nombre: 'Pimiento amarillo crudo chico',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 75,
      peso_neto_g: 64,
      energia_kcal: 17,
      proteina_g: 0.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.0,
      fibra_g: 0.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10125': AlimentoItem(
    id: '10125',
    nombre: 'Pimiento cocido',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 68,
      peso_neto_g: 68,
      energia_kcal: 19,
      proteina_g: 0.6,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.6,
      fibra_g: 0.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10126': AlimentoItem(
    id: '10126',
    nombre: 'Pimiento fresco',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 60,
      peso_neto_g: 60,
      energia_kcal: 17,
      proteina_g: 0.5,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.8,
      fibra_g: 1.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10127': AlimentoItem(
    id: '10127',
    nombre: 'Pimiento rojo crudo chico',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 75,
      peso_neto_g: 64,
      energia_kcal: 17,
      proteina_g: 0.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.0,
      fibra_g: 0.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10128': AlimentoItem(
    id: '10128',
    nombre: 'Pimiento verde crudo chico',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	pieza	',
      peso_bruto_g: 75,
      peso_neto_g: 64,
      energia_kcal: 17,
      proteina_g: 0.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.0,
      fibra_g: 0.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10129': AlimentoItem(
    id: '10129',
    nombre: 'Poro crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	taza	',
      peso_bruto_g: 40,
      peso_neto_g: 32,
      energia_kcal: 21,
      proteina_g: 0.5,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.5,
      fibra_g: 1.2,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10130': AlimentoItem(
    id: '10130',
    nombre: 'Puerro crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	pieza	',
      peso_bruto_g: 22,
      peso_neto_g: 22,
      energia_kcal: 14,
      proteina_g: 0.3,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.2,
      fibra_g: 0.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10131': AlimentoItem(
    id: '10131',
    nombre: 'Puerro hervido sin sal',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	pieza	',
      peso_bruto_g: 62,
      peso_neto_g: 62,
      energia_kcal: 19,
      proteina_g: 0.5,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.7,
      fibra_g: 0.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10132': AlimentoItem(
    id: '10132',
    nombre: 'Puré de tomate enlatado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 4,
      unidad: '	taza	',
      peso_bruto_g: 63,
      peso_neto_g: 63,
      energia_kcal: 24,
      proteina_g: 1.0,
      lipidos_g: 0.1,
      hidra_carbo_g: 5.6,
      fibra_g: 1.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10133': AlimentoItem(
    id: '10133',
    nombre: 'Quelite crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 80,
      unidad: '	g	',
      peso_bruto_g: 80,
      peso_neto_g: 66,
      energia_kcal: 26,
      proteina_g: 3.1,
      lipidos_g: 0.3,
      hidra_carbo_g: 2.6,
      fibra_g: 0.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10134': AlimentoItem(
    id: '10134',
    nombre: 'Rábano crudo rebanado',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 116,
      peso_neto_g: 104,
      energia_kcal: 17,
      proteina_g: 0.7,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.5,
      fibra_g: 1.7,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10135': AlimentoItem(
    id: '10135',
    nombre: 'Romerito crudo',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 120,
      unidad: '	g	',
      peso_bruto_g: 120,
      peso_neto_g: 72,
      energia_kcal: 26,
      proteina_g: 2.6,
      lipidos_g: 0.1,
      hidra_carbo_g: 3.5,
      fibra_g: 0.7,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10136': AlimentoItem(
    id: '10136',
    nombre: 'Salsa de chile',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 115,
      peso_neto_g: 115,
      energia_kcal: 28,
      proteina_g: 1.2,
      lipidos_g: 0.2,
      hidra_carbo_g: 5.2,
      fibra_g: 2.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10137': AlimentoItem(
    id: '10137',
    nombre: 'Salsifí',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 35,
      unidad: '	g	',
      peso_bruto_g: 35,
      peso_neto_g: 23,
      energia_kcal: 18,
      proteina_g: 0.3,
      lipidos_g: 0.0,
      hidra_carbo_g: 4.0,
      fibra_g: 0.4,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10138': AlimentoItem(
    id: '10138',
    nombre: 'Semilla de guaje verde',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 5,
      unidad: '	g	',
      peso_bruto_g: 65,
      peso_neto_g: 29,
      energia_kcal: 28,
      proteina_g: 2.5,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.0,
      fibra_g: 0.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10139': AlimentoItem(
    id: '10139',
    nombre: 'Setas cocidas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 78,
      peso_neto_g: 78,
      energia_kcal: 21,
      proteina_g: 2.5,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.4,
      fibra_g: 2.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10140': AlimentoItem(
    id: '10140',
    nombre: 'Setas crudas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 100,
      unidad: '	g	',
      peso_bruto_g: 100,
      peso_neto_g: 85,
      energia_kcal: 23,
      proteina_g: 2.7,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.7,
      fibra_g: 2.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10141': AlimentoItem(
    id: '10141',
    nombre: 'Tomate verde',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 5,
      unidad: '	pieza	',
      peso_bruto_g: 100,
      peso_neto_g: 86,
      energia_kcal: 21,
      proteina_g: 0.9,
      lipidos_g: 0.2,
      hidra_carbo_g: 3.9,
      fibra_g: 2.1,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10142': AlimentoItem(
    id: '10142',
    nombre: 'Tomatitos (tomatiles)',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 75,
      unidad: '	g	',
      peso_bruto_g: 75,
      peso_neto_g: 65,
      energia_kcal: 26,
      proteina_g: 2.3,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.1,
      fibra_g: 0.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10143': AlimentoItem(
    id: '10143',
    nombre: 'Verdolaga cocida',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1,
      unidad: '	taza	',
      peso_bruto_g: 115,
      peso_neto_g: 115,
      energia_kcal: 21,
      proteina_g: 1.7,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.1,
      fibra_g: 0.9,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10144': AlimentoItem(
    id: '10144',
    nombre: 'Verdolaga cruda limpia',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 192,
      peso_neto_g: 192,
      energia_kcal: 31,
      proteina_g: 2.5,
      lipidos_g: 0.2,
      hidra_carbo_g: 6.6,
      fibra_g: 1.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10145': AlimentoItem(
    id: '10145',
    nombre: 'Verdura (mexcla) congelada, cocida sin sal',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 46,
      peso_neto_g: 46,
      energia_kcal: 30,
      proteina_g: 1.3,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.6,
      fibra_g: 2.0,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10146': AlimentoItem(
    id: '10146',
    nombre: 'Xoconostle',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 3,
      unidad: '	pieza	',
      peso_bruto_g: 102,
      peso_neto_g: 71,
      energia_kcal: 18,
      proteina_g: 0.1,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.7,
      fibra_g: 1.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10147': AlimentoItem(
    id: '10147',
    nombre: 'Yemitas (hongos) crudas',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 2,
      unidad: '	taza	',
      peso_bruto_g: 160,
      peso_neto_g: 160,
      energia_kcal: 27,
      proteina_g: 4.8,
      lipidos_g: 1.7,
      hidra_carbo_g: 6.4,
      fibra_g: 3.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10148': AlimentoItem(
    id: '10148',
    nombre: 'Yerbamora cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 50,
      unidad: '	g	',
      peso_bruto_g: 50,
      peso_neto_g: 41,
      energia_kcal: 21,
      proteina_g: 2.0,
      lipidos_g: 0.3,
      hidra_carbo_g: 3.6,
      fibra_g: 0.6,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10149': AlimentoItem(
    id: '10149',
    nombre: 'Zanahoria miniatura cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 4,
      unidad: '	pieza	',
      peso_bruto_g: 60,
      peso_neto_g: 60,
      energia_kcal: 21,
      proteina_g: 0.4,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.9,
      fibra_g: 1.7,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10150': AlimentoItem(
    id: '10150',
    nombre: 'Zanahoria picada cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 64,
      peso_neto_g: 64,
      energia_kcal: 26,
      proteina_g: 0.6,
      lipidos_g: 0.2,
      hidra_carbo_g: 4.3,
      fibra_g: 1.8,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
  '10151': AlimentoItem(
    id: '10151',
    nombre: 'Zanahoria rallada cruda',
    esFavorito: false,
    clasificacion: 0,
    porcion: 1,
    categoria: TIPO_ALIMENTO_LIST[1],
    resumen: Resumen(
      cant_suge: 1 / 2,
      unidad: '	taza	',
      peso_bruto_g: 55,
      peso_neto_g: 55,
      energia_kcal: 23,
      proteina_g: 0.5,
      lipidos_g: 0.1,
      hidra_carbo_g: 4.1,
      fibra_g: 1.5,
      sodio_mg: 0,
      colesterol_mg: 0,
    ),
  ),
};
